In [2]:
# Cargo las librerías básicas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Cargo librerías para el preprocesamiento de datos
from sklearn.model_selection import train_test_split # Dividir los datos en conjuntos de entrenamiento y prueba
from sklearn.preprocessing import StandardScaler # Estandarización de características
from sklearn.impute import SimpleImputer # Manejo de valores faltantes
# Si es necesario, cargo librerías de datasets de ejemplo
from sklearn.datasets import load_iris # Dataset de ejemplo (Iris)

# Si es necesario, cargo librerías para la ingeniería de características (Opcional)
from sklearn.preprocessing import OneHotEncoder # Codificación de variables categóricas
# Cargo librerías para la construcción de modelos
from sklearn.linear_model import LinearRegression # Algoritmo que usaremos en el estudio. Regresión lineal
# Cargo librerías para la evaluación de modelos
from sklearn import metrics # Métricas de evaluación

### Cargar u obtener el Dataset

In [3]:
def leer_boston():
    ulr = "https://lib.stat.cmu.edu/datasets/boston" # URL del dataset de Boston
    df = pd.read_csv(ulr, sep="\s+", skiprows=22, header=None) # Leo el dataset, uso separador de espacios, salto las primeras 22 filas y no uso encabezados
    # El dataset tiene una estructura especial, por lo que se necesita un procesamiento adicional
    # El conjunto de datos tiene 14 columnas, las primeras 13 son características y la última es el valor objetivo (precio de la vivienda)
    # Los datos están organizados en bloques de 2 filas por muestra
    data = np.hstack([df.values[::2, :], df.values[1::2, :2]]) # Combino las filas pares e impares. Está cogiendo todas las columnas de las filas pares y las dos primeras columnas de las filas impares
    target = df.values[1::2, 2] # El valor objetivo está en la segunda fila de cada bloque
    return {'data': data, 'target': target, "feature_names": ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT"]} # Retorno un diccionario con los datos y el objetivo

In [4]:
data = leer_boston()
df = pd.DataFrame(data['data'], columns=data['feature_names']) # Características
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [5]:
df['MEDV'] = data['target'] # Agrego la columna del valor objetivo al DataFrame
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

Cargarlo desde el fichero housing.csv

In [7]:
df2 = pd.read_csv("../datasets/housing.csv", header=None, names=data['feature_names'] + ['MEDV']) # Cargo el dataset de viviendas de Boston desde un archivo local
df2.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632 18.00 2.310 0 0.5380 6.5750 65...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.02731 0.00 7.070 0 0.4690 6.4210 78...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.02729 0.00 7.070 0 0.4690 7.1850 61...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.03237 0.00 2.180 0 0.4580 6.9980 45...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.06905 0.00 2.180 0 0.4580 7.1470 54...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN